version: "3"

services:
  app:
    build: .
    container_name: simulator
    networks:
      - codedelivery
    volumes:
      - .:/go/src/
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
networks:
  codedelivery:
    name: codedelivery
    driver: bridge
